### ISSUE TITLE
Errors encountered when installing:

### ISSUE THREAD

**Issue by matthew-dean** [storybook-vue/nuxt#47]
I encountered the following errors:
1. `Error: Could not evaluate the @storybook-vue/nuxt package from the 'framework' field of Storybook config. Are you sure it's a valid package and is installed?`
2. `sh: storybook-nuxt: command not found`
3. The `stories` property of `StorybookConfig` has an error: `Object literal may only specify known properties, and 'stories' does not exist in type 'StorybookConfig'`
4. The `preview.ts` has an error: `Module '"@storybook-vue/nuxt"' has no exported member 'Preview'`

Eventually I got Storybook started by downgrading Storybook to a non-alpha version, and manually installing the `storybook-nuxt` cli package, but...

Instead of rendering the story, Storybook renders, for the story, a Nuxt 404 page.

**Comment by moifort** [comment]
I encountered the same error, change your import and configuration in `.storybook/main.ts` by `@storybook-nuxt/framework`  instead of `@storybook-vue/nuxt`.

But still have not working storybook, I continue digging...

**Comment by chakAs3** [comment]
@matthew-dean @moifort   Sorry i was publishing for 2 namespaces, please try again,  i released new version

**Comment by chakAs3** [comment]
use can test this on [Stackbliz](https://stackblitz.com/~/github.com/storybook-vue/storybook-nuxt/pull/49)

**Comment by rezkileap** [comment]
I tried this earlier to bootstrap a new project and still does not work. same issue thought `Error: Could not evaluate the @storybook-vue/nuxt package from the 'framework' field of Storybook config. Are you sure it's a valid package and is installed?`
